site_name: VULKИ Documentation
theme:
  name: material
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
extra_css:
  - css/extra.css

nav:
  - Welcome to VULKИ: index.md
  - Getting Started: getting_started.md

  - Data Types & Variables:
    - Overview: types/overview.md
    - Operators: types/operators.md
    - Types:
      - String: types/string.md
      - Date & Time: todo.md
      - Boolean: todo.md
      - Integers: todo.md
      - Floats: todo.md
      - UUID: types/uuid.md
      - URL: todo.md
      - JSON: todo.md
      - Arrays: todo.md
      - Array Vectors: types/array_vectors.md
      - Tables: todo.md
    - Type Conversion: todo.md
  - Functions:
      - Misc functions: todo.md
      - Array functions: todo.md
      - Geo functions: todo.md
      - Encoding functions: todo.md
      - Bitmap functions: todo.md
      - Aggregate functions: todo.md
      - Extensions:
        - Vector functions: todo.md
  - DataTables:
    - Overview: datatables/overview.md
    - Reference: datatables/reference.md
    - Joins: datatables/joins.md
    - Query Execution, Parameters and Caching: datatables/execution.md
    - Working with results: datatables/recordset.md
    - Creating tables: datatables/creating.md
  - Importing Data: loading.md
  - The Vulkn CLI & Workspaces: workspaces.md
  - DataOps Extensions:
    - Introduction: extensions/about.md
    - SQL:
      - CHUNK BY: extensions/chunk_by.md
      - VECTORIZE BY: extensions/vectorize_by.md
  - Data Storage:
    - Engines Overview: todo.md
    - Memory: todo.md
    - Log Engines:
      - TinyLog: todo.md
      - Log: todo.md
      - StripeLog: todo.md
    - Specialised Engines:
      - Set: todo.md
      - Join: todo.md
    - MergeTree Engines:
      - MergeTree: todo.md
      - ReplacingMergeTree: todo.md
      - SummingMergeTree: todo.md
      - AggregatingMergeTree: todo.md
      - CollapsingMergeTree: todo.md
  - Object Management & Profiling: dbmanagement.md
  - System Management: system_management.md
  - Examples: todo.md