#!/bin/bash

# Copyright (c) 2019, Jason Godden <jason@godden.id.au>
# Copyright (c) 2019, VulknData Pty Ltd
# GNU General Public License v3.0 (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-only


export PYTHONDONTWRITEBYTECODE=1
export CWD=$(cd `dirname $0` && pwd)
export PYTHONPATH=../:$PYTHONPATH
export PYTHONSTARTUP=$CWD/../vulkn/apps/vulkn.py

python3 -q - "$@"

