#!/bin/bash

# Copyright (c) 2019, Jason Godden <jason@godden.id.au>
# Copyright (c) 2019, VulknData Pty Ltd
# GNU General Public License v3.0 (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-only


for P in $(which python3.7 python3.8 python3.9 | sort)
do
        VULKN_APP=$($P -c 'import vulkn; print(vulkn.__file__)' 2>/dev/null)
        if [[ $VULKN_APP != "" ]]
        then
                PYTHON=$P
                VULKN_ROOT=$(dirname $VULKN_APP)
                break
        fi
done

export PYTHONSTARTUP=$VULKN_ROOT/apps/vulkn.py

exec $PYTHON -q - "$@"
